version: '3'

services:
  ftp:
    image: bloodhunterd/froxlor-ftp
    environment:
      - TZ: 'Europe/Berlin'
      - FRX_WEB_DIR: '/var/customers/webs'
      - FRX_DB_HOST: localhost
      - FRX_DB_NAME: froxlor
      - FRX_DB_USER: froxlor
      - FRX_DB_PASSWORD: ''
      - SERVER_NAME: 'Froxlor FTP Server'
    volumes:
      - ./webs:/var/customers/webs/
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
    ports:
      - 21
    restart: unless-stopped
